#What is Numpy?


NumPy is a python library that provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

In other words, NumPy is a very important core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve computational mathematical problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

We will see NumPy in action with different examples.




#Creating a normal List

>




In [ ]:
my_list=[1,2,3]
my_list


[1, 2, 3]

#Casting a normal python list into a NumPy array

NumPy library follows an import convention: when you import this library, you have to make sure that you import it as **np**. By doing this, you’ll make sure that other Pythonistas understand your code more easily.

In [ ]:
import numpy as np
a=np.array(my_list)


In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
s=np.array(my_mat)

#NumPy own genatation method

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#NumPy also provides many functions to create arrays:

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((4,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(5) #identitity matrix(2d square matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#creating arrays of random numbers
np.random.rand(5) #uniform distribution from 0 to 1

array([0.56589676, 0.21380228, 0.36122829, 0.81842676, 0.07930536])

In [ ]:
#creating arrays of random numbers
np.random.rand(5,5) # 2D uniform distribute from 0 to 1

array([[0.81565599, 0.45359242, 0.68177353, 0.55046299, 0.88186574],
       [0.72497207, 0.62359289, 0.19768745, 0.26740449, 0.87618588],
       [0.39397703, 0.30230744, 0.5940924 , 0.16378247, 0.57788044],
       [0.1946473 , 0.15318055, 0.96188762, 0.33818409, 0.19333619],
       [0.76057971, 0.2199619 , 0.26982591, 0.01582078, 0.22598602]])

In [ ]:
#creating arrays of random numbers
np.random.randn(4) # standard normal distribution range from -infinty to infinity

array([-0.2000559 , -0.45898359,  0.03309988,  0.48908857])

In [ ]:
#creating arrays of random numbers
np.random.randint(1,100,20)

array([19, 35, 58, 69, 60, 41, 18,  3, 23, 90, 76,  7, 91,  3,  4, 95, 97,
       41, 58,  9])

In [ ]:
#gives you 6 numbers randomly from 0-(10-1)
x1 = np.random.randint(10, size=6)
x1

array([7, 0, 9, 6, 4, 5])

In [ ]:
x2 = np.random.randint(10, size=(3,4,3))
print(x2)
print(x2.shape)
print(f"Dimensiion = {x2.ndim}")

[[[0 8 2]
  [7 3 7]
  [9 2 3]
  [3 4 1]]

 [[6 8 6]
  [5 8 6]
  [6 0 3]
  [2 9 0]]

 [[3 3 1]
  [6 0 0]
  [1 5 6]
  [9 1 9]]]
(3, 4, 3)
Dimensiion = 3


In [ ]:
#creating max and min value in array
my_arr=np.array([1,-3,4,5,3,4,56,7,-34])
print(my_arr.min())
print(my_arr.max())

-34
56


In [ ]:
#returning index number max and min value in array
print(my_arr.argmin())
print(my_arr.argmax())

8
6


In [ ]:
#how to find the shape of vector?
my_arr.shape

(9,)

In [ ]:
#how to reshape vector?
my_arr.reshape(3,3)


array([[  1,  -3,   4],
       [  5,   3,   4],
       [ 56,   7, -34]])

In [ ]:
#how to know  what the data type value we have in array ?
print(type(my_arr))
print(my_arr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
#append
import numpy as np
new_arr=np.arange(1,11)
print(new_arr)
new_arr= np.append(new_arr,[100,20,30])
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10 100  20  30]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[400],[800]])
print(b)
newarr = np.append(a, b,axis=1 )
print(newarr)

[[1 2 3]
 [4 5 6]]
[[400]
 [800]]
[[  1   2   3 400]
 [  4   5   6 800]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[400],[800]])
newarr = np.append(a, b)
print(newarr)

[  1   2   3   4   5   6 400 800]


In [ ]:
#insert
a= np.array([1 , 2, 3])
print( a)
new_array= np.insert(a,1,50)
print(new_array)

[1 2 3]
[ 1 50  2  3]


In [ ]:
#delete
import numpy as np
a = np.array([[1,2,3],[4,5,6],[10,20,30]])

print(a)
narr = np.delete(a,1,axis=0)
print(narr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[ 1  2  3]
 [10 20 30]]


In [ ]:
#finding the index of a value in the array usin where() method
a = np.array([1 , 2 ,3, 5 ,4 ,5])
print(np.where(a==5))

(array([3, 5]),)


#NumPy Indexing and Selection


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[1,0]

4

In [ ]:
a[1:,1:]


array([[5, 6],
       [8, 9]])

In [ ]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#conditional selection
b = a > 2  #take an array and combine with conditional operate to get a boolean values/arrays
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#return only those elements those were true using bollean array
x=a[b]
x.shape

(7,)

In [ ]:
#in one go!!
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.array([[1,2,3],[4,5,6],[9,10,11]])
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]


In [ ]:

a1[a1<=2]=1
a1[a1>2]=0
a1

array([[1, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

#NumPy Operations

In [ ]:
import numpy as np
arr=np.arange(0,11)
arr2=np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#addition
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#substraction
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#multiplication
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#scaling an array
arr+100
#to the power
#squareroot
#sin
#log
#max/min


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

For more info: https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

#NumPy Official Doc: https://numpy.org/doc/stable/user/index.html